# Generated by Django 6.0.7 on 2026-07-11 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_claimed', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Insurance', 'Insurance'), ('Write-off', 'Write-off')], default='Pending', max_length=20)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.visit')),
            ],
        ),
    ]
